version: '2'
services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 5000:5000
        restart: always
 
    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always
 
    node:
        depends_on:
            - reverseproxy
        image: sjukic1/getting-started:latest
        ports:
            - 3000:3000
        restart: always
    
    bulletin:
        depends_on:
            - reverseproxy
        image: prvi:latest
        ports:
            - 8080:8080
        restart: always
    